name: .NET Release

on: create

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore dependencies
        run: dotnet restore Dap
      - name: Build
        run: dotnet build Dap -c Release --no-restore
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Dap-${{ github.ref_name }}-NetStandard20
          path: Dap/bin/Release/
  upload:
    name: Upload Generated Sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy licenses
        run: cp LICENSE* Dap/
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: Dap-${{ github.ref_name }}
          path: |
            Dap/*.csproj
            Dap/*.cs
            Dap/LICENSE*
